#!/usr/bin/python3
import click
import git
import os
import subprocess


@click.group()
def cmd():
    pass


@cmd.command()
def init():
    repo = subprocess.run('git rev-parse --show-toplevel',
                          shell=True,
                          stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE)

    if repo.returncode != 0:
        git.Repo.init()
        click.echo('init git repo')
    else:
        click.echo('Error: already initialized git repo')


@cmd.command()
def major():
    click.echo('major')


@cmd.command()
def minor():
    click.echo('minor')


@cmd.command()
def patch():
    click.echo('patch')


@cmd.command()
def commit():
    click.echo('commit')


@cmd.command()
def cancel():
    click.echo('cancel')


@cmd.command()
def push():
    click.echo('push')


def main():
    cmd()


if __name__ == '__main__':
    # repo = git.Repo('./')
    main()
