#!/usr/bin/python3
import click
import git
import os


@click.group()
def cmd():
    pass


@cmd.command()
def init():
    click.echo('init')


@cmd.command()
def major():
    click.echo('major')


@cmd.command()
def minor():
    click.echo('minor')


@cmd.command()
def patch():
    click.echo('patch')


@cmd.command()
def commit():
    click.echo('commit')


@cmd.command()
def cancel():
    click.echo('cancel')


@cmd.command()
def push():
    click.echo('push')


def main():
    cmd()


if __name__ == '__main__':
    repo = git.Repo('./')
    main()
